feat!: install `ppx_expect`
returntocorp/ocaml-layer pull request #29
Opened 2023-06-12 21:54 UTC by brandonspark

This PR installs `ppx_expect`, which I added to Semgrep in https://github.com/returntocorp/semgrep/commit/b70e51f97dad115304f712cb10434a51b68d8d08

PR checklist:

- [] PR comment includes a reproducible test plan
- [X] Change has no security implications (otherwise ping the security team)

2023-06-13 07:56 UTC, aryx requested changes
While you're at it, can you also notty and a few other packages
that were added recently in semgrep.opam?
emile, bos, digestif, odoc
and I probably miss some.

2023-06-13 18:18 UTC, aryx approved these changes

2023-06-13 22:58 UTC, brandonspark commented
@aryx no permission to merge

2023-06-14 08:05 UTC, merged

2023-06-14 08:06 UTC, aryx commented
@mjambon can we add the admin or maintain property to developers for this repo?
So brandon and other can also merge without us.